version: '3.3'

services:
  db:
    container_name: db-binotify
    build:
      context: .
      dockerfile: Dockerfile
    image: db-binotify:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3312:3312

  adminer-test:
    container_name: adminer-test
    image: adminer:4.8.1
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - 8090:8090

volumes:
  databases: