version: '3.3'

services:
  db:
    container_name: db-binotify
    build:
      context: .
      dockerfile: Dockerfile
    image: db-binotify:latest

    environment:
      MYSQL_USER: tubes
      MYSQL_PASSWORD: tubes
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3312:3306


  adminer:
    container_name: adminer
    image: adminer:4.8.1
    environment:
      ADMINER_DEFAULT_SERVER: db-binotify
    restart: always
    ports:
      - 8080:8080
